version: '3.9'

services:
  cowdemo:
    container_name: demo
    image: demo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8001:8080
    networks:
      - cownetwork

networks:
  cownetwork:
    external: true
    driver: bridge
